version: '2'

services: 
  ruby: 
    build: 
      context: ./
      dockerfile: docker/ruby/Dockerfile
    volumes:
      - ./application:/app
    environment: 
      SLACK_API_KEY: ${SLACK_API_KEY}
    command: ruby app.rb